#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PACKAGE_JSON="$ROOT_DIR/package.json"
CHANGELOG="$ROOT_DIR/CHANGELOG.md"
README_FILE="$ROOT_DIR/README.md"

DEFAULT_REVIEW_PATTERNS='TODO|FIXME|WIP|copilot|windsurf|chatgpt|claude|generated by ai|ai-generated|copied from flutter|cloned from flutter|/Users/'

PUBLISH_MODE="dry-run"
VERSION_ARG=""
SKIP_TESTS="false"
SKIP_REVIEW="false"
CREATE_TAG="false"
PUSH_TAG="false"
CREATE_GITHUB_RELEASE="false"
VERIFY_INSTALL="false"

usage() {
  cat <<'EOF'
Usage:
  ./scripts/publish-release.sh [options]

Options:
  --patch               Bump patch version
  --minor               Bump minor version
  --major               Bump major version
  --version X.Y.Z       Set an explicit version
  --publish             Full release: publish, tag, push tag, GitHub release, verify install
  --skip-tests          Skip build verification
  --skip-review         Skip text review scan
  --tag                 Create a git tag after publish
  --push-tag            Push the git tag after publish
  --github-release      Create a GitHub release with gh after publish
  --verify-install      Verify published package in a temp test app
  --help                Show this help

Examples:
  ./scripts/publish-release.sh --patch
  ./scripts/publish-release.sh --minor --publish
  ./scripts/publish-release.sh --patch --publish
  ./scripts/publish-release.sh --version 1.2.0
EOF
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

read_package_field() {
  local field="$1"
  node -e "const pkg=require(process.argv[1]); const value=pkg[process.argv[2]]; if (typeof value === 'string') process.stdout.write(value);" "$PACKAGE_JSON" "$field"
}

confirm() {
  local message="$1"
  local reply
  printf "%s [y/N]: " "$message"
  read -r reply
  [[ "$reply" == "y" || "$reply" == "Y" ]]
}

has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

search_review_patterns() {
  local output_file="$1"

  if has_cmd rg; then
    rg -n -S \
      -g '!node_modules/**' \
      -g '!.git/**' \
      -g '!lib/**' \
      -g '!.derived-data/**' \
      -g '!example-app/ios/**' \
      -g '!example-app/android/**' \
      -g '!scripts/publish-release.sh' \
      -g '!docs/release.md' \
      -g '!docs/publish-checklist.md' \
      "$DEFAULT_REVIEW_PATTERNS" "$ROOT_DIR" >"$output_file"
  else
    grep -RInE "$DEFAULT_REVIEW_PATTERNS" "$ROOT_DIR" \
      --exclude-dir=node_modules \
      --exclude-dir=.git \
      --exclude-dir=lib \
      --exclude-dir=.derived-data \
      --exclude=publish-release.sh \
      --exclude=release.md \
      --exclude=publish-checklist.md >"$output_file"
  fi
}

print_section() {
  printf '\n==> %s\n' "$1"
}

git_tag_exists() {
  local tag_name="$1"
  git rev-parse "$tag_name" >/dev/null 2>&1
}

verify_installation() {
  local package_name="$1"
  local version="$2"
  local temp_dir

  print_section "Verifying published package install"

  temp_dir="$(mktemp -d)"
  echo "Using temp directory: $temp_dir"

  (
    cd "$temp_dir"
    npm init -y >/dev/null 2>&1
    npm install "${package_name}@${version}"
  )

  echo "Install verification passed."
  rm -rf "$temp_dir"
}

create_github_release() {
  local version="$1"
  local tag_name="v$version"
  local release_notes

  if ! has_cmd gh; then
    echo "GitHub CLI (gh) is not installed. Skipping GitHub release." >&2
    return
  fi

  release_notes="$(mktemp)"
  awk -v heading="## [$version]" '
    $0 == heading { capture=1; next }
    capture && /^## \[/ { exit }
    capture { print }
  ' "$CHANGELOG" >"$release_notes"

  if [[ ! -s "$release_notes" ]]; then
    echo "Could not extract release notes for $version from CHANGELOG.md. Skipping GitHub release." >&2
    rm -f "$release_notes"
    return
  fi

  print_section "Creating GitHub release"
  gh release create "$tag_name" --title "$tag_name" --notes-file "$release_notes"
  rm -f "$release_notes"
}

review_scan() {
  print_section "Running review scan"

  local findings_file
  findings_file="$(mktemp)"

  if search_review_patterns "$findings_file"; then
    echo "Potential review findings:"
    cat "$findings_file"
    rm -f "$findings_file"
    echo
    echo "Please review these findings before publishing." >&2
    exit 1
  fi

  rm -f "$findings_file"
  echo "Review scan passed."
}

validate_changelog_for_version() {
  local version="$1"
  local today
  today="$(date '+%Y-%m-%d')"

  if ! grep -Fq "## [$version]" "$CHANGELOG"; then
    echo "CHANGELOG.md does not contain an entry for version $version" >&2
    exit 1
  fi

  if ! grep -Fq "## [$version] - $today" "$CHANGELOG"; then
    echo "CHANGELOG.md entry for $version does not use today's date ($today)." >&2
    echo "Please update $CHANGELOG before publishing." >&2
    exit 1
  fi

  echo "CHANGELOG entry for $version looks good."
}

show_summary() {
  local version="$1"
  local package_name="$2"

  print_section "Release summary"
  echo "Package: $package_name"
  echo "Version: $version"
  echo "Mode: $PUBLISH_MODE"
  echo "README: $README_FILE"
  echo "CHANGELOG: $CHANGELOG"
  echo
  echo "Notes:"
  echo "- This script updates package.json using npm version with --no-git-tag-version."
  echo "- It does not create a git commit automatically."
  echo "- It runs npm pack --dry-run before publish."
  echo "- If --publish is not provided, it stops after the dry run."
  echo "- In publish mode it also tags, pushes the tag, tries GitHub release, and verifies installation."
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --patch)
        VERSION_ARG="patch"
        shift
        ;;
      --minor)
        VERSION_ARG="minor"
        shift
        ;;
      --major)
        VERSION_ARG="major"
        shift
        ;;
      --version)
        VERSION_ARG="${2:-}"
        [[ -n "$VERSION_ARG" ]] || { echo "Missing value for --version" >&2; exit 1; }
        shift 2
        ;;
      --publish)
        PUBLISH_MODE="publish"
        CREATE_TAG="true"
        PUSH_TAG="true"
        CREATE_GITHUB_RELEASE="true"
        VERIFY_INSTALL="true"
        shift
        ;;
      --skip-tests)
        SKIP_TESTS="true"
        shift
        ;;
      --skip-review)
        SKIP_REVIEW="true"
        shift
        ;;
      --tag)
        CREATE_TAG="true"
        shift
        ;;
      --push-tag)
        CREATE_TAG="true"
        PUSH_TAG="true"
        shift
        ;;
      --github-release)
        CREATE_TAG="true"
        CREATE_GITHUB_RELEASE="true"
        shift
        ;;
      --verify-install)
        VERIFY_INSTALL="true"
        shift
        ;;
      --help)
        usage
        exit 0
        ;;
      *)
        echo "Unknown option: $1" >&2
        usage
        exit 1
        ;;
    esac
  done
}

parse_args "$@"

require_cmd npm
require_cmd date
require_cmd node

cd "$ROOT_DIR"

PACKAGE_NAME="$(read_package_field name)"
CURRENT_VERSION="$(read_package_field version)"

print_section "Current package info"
echo "Package: $PACKAGE_NAME"
echo "Current version: $CURRENT_VERSION"

if [[ -z "$VERSION_ARG" ]]; then
  echo "No version bump option provided." >&2
  usage
  exit 1
fi

print_section "Updating version"
if [[ "$VERSION_ARG" =~ ^(patch|minor|major)$ ]]; then
  npm version "$VERSION_ARG" --no-git-tag-version
else
  if [[ "$VERSION_ARG" == "$CURRENT_VERSION" ]]; then
    echo "Version already set to $CURRENT_VERSION. Keeping current version for first publish."
  else
    npm version "$VERSION_ARG" --no-git-tag-version
  fi
fi

NEW_VERSION="$(read_package_field version)"
echo "Updated version: $CURRENT_VERSION -> $NEW_VERSION"

if [[ "$SKIP_REVIEW" != "true" ]]; then
  review_scan
fi

print_section "Checking release notes"
validate_changelog_for_version "$NEW_VERSION"

if [[ ! -f "$README_FILE" ]]; then
  echo "README.md not found." >&2
  exit 1
fi

if [[ "$SKIP_TESTS" != "true" ]]; then
  print_section "Building package"
  npm run prepare
fi

print_section "Previewing npm package contents"
npm pack --dry-run

show_summary "$NEW_VERSION" "$PACKAGE_NAME"

if [[ "$PUBLISH_MODE" != "publish" ]]; then
  print_section "Dry run complete"
  echo "No publish performed."
  echo "When ready, run:"
  echo "  ./scripts/publish-release.sh --version $NEW_VERSION --publish"
  exit 0
fi

print_section "Checking npm authentication"
npm whoami

if ! confirm "Proceed with npm publish for $PACKAGE_NAME@$NEW_VERSION?"; then
  echo "Publish cancelled."
  exit 1
fi

print_section "Publishing to npm"
npm publish

TAG_NAME="v$NEW_VERSION"

if [[ "$CREATE_TAG" == "true" ]]; then
  print_section "Creating git tag"
  if git_tag_exists "$TAG_NAME"; then
    echo "Git tag $TAG_NAME already exists. Skipping tag creation." >&2
  else
    git tag "$TAG_NAME"
    echo "Created tag $TAG_NAME"
  fi
fi

if [[ "$PUSH_TAG" == "true" ]]; then
  print_section "Pushing git tag"
  git push origin "$TAG_NAME"
fi

if [[ "$CREATE_GITHUB_RELEASE" == "true" ]]; then
  create_github_release "$NEW_VERSION"
fi

if [[ "$VERIFY_INSTALL" == "true" ]]; then
  verify_installation "$PACKAGE_NAME" "$NEW_VERSION"
fi

print_section "Publish complete"
echo "Published $PACKAGE_NAME@$NEW_VERSION"
echo
echo "Recommended next steps:"
echo "1. Commit the version/changelog changes"
echo "2. Push your branch"
echo "3. Ensure tag/release are created if you did not use the script options"
echo "4. Verify installation with npm install $PACKAGE_NAME@$NEW_VERSION"
